FROM gcc:latest
USER root
COPY ["interferometroserial4.cpp", "C:/Users/Iago Leal/Desktop/TCC/TCC/SerialComApp/"]
RUN mkdir -p C:/Users/Iago Leal/Desktop/TCC/TCC/SerialComApp/
WORKDIR C:/Users/Iago Leal/Desktop/TCC/TCC/SerialComApp/
RUN g++ -o serial_app interferometroserial4.cpp
CMD ["./serial_app"]

# FROM gcc:4.9
# COPY . /usr/src/myapp
# WORKDIR /usr/src/myapp
# RUN gcc -o myapp main.c
# CMD ["./myapp"]

# C:\Users\Iago Leal\Desktop\TCC\TCC8.0\SerialComApp\Teste
# docker build -t serial_app .
# docker run -it --rm --name serial_app serial_app
# docker run -it --rm -v "//c/users/iago leal/desktop/tcc/tcc/serialcomapp/" -w "//C/Users/Iago Leal/Desktop/TCC/TCC/SerialComApp/" gcc:latest g++ -o serial_app interferometroserial2.cpp